tolerations:
  - key: "node-role"
    operator: "Equal"
    value: "infra"
    effect: "NoSchedule"

config:
  clients:
    - url: http://otus-k8s-platform-loki.loki.svc.cluster.local:3100/loki/api/v1/push
